model:
  meta_architecture: ResNet18
datasets:
  train: ("CIFAR10_TRAIN",)
  test: "CIFAR10_TEST"
dataloader:
  num_workers: 4
input:
  do_normalize: False
  min_size_train: (32,)
  max_size_train: 32
  min_size_test: 32
  max_size_test: 32
solver:
  loss_function: "cross_entropy_loss"
  metric_functions: ("accuracy",)
  batch_size: 128
  num_epochs: 10
  trainer: cifar10
test:
  batch_size: 128
  evaluator: "cifar10"